    # Use an official OpenJDK runtime as the base image. Choose a version compatible with your Spring Boot application.
    FROM openjdk:17-jdk-slim

    # Set the working directory inside the container.
    WORKDIR /app

    # Copy the executable JAR file from your build output to the container.
    # Replace 'your-application-name.jar' with the actual name of your generated JAR file.
    COPY target/helloworld-0.0.1-SNAPSHOT.jar app.jar

    # Expose the port on which your Spring Boot application listens (default is 8080).
    EXPOSE 9090

    # Define the command to run the application when the container starts.
    ENTRYPOINT ["java", "-jar", "app.jar"]
